### PR TITLE
Multi-Arch Support, Initially Supporting AMD64 and AArch64

### PR DESCRIPTION
**Pull request by ekristen**
### Included

* Adds support for building image for multiple architectures
  * Initial support for amd64 and aarch64 (see below for aarch64)
* Each architecture gets it's own ...
  * tag (format: tag-${ARCH})
  * Dockerfile (format: package/${ARCH}/Dockerfile)

### Not Included

* Manifest creation / pushing

### Manifest Creation / Pushing

Manifests can be created by using a tool like https://github.com/estesp/manifest-tool and example spec file that could be generated and used by `./manifest-tool push from-spec spec.yml`

```yaml
image: rancher/rke-tools:dev
manifests:
  - image: rancher/rke-tools:dev-amd64
    platform:
      architecture: amd64
      os: linux
  - image: rancher/rke-tools:dev-aarch64
    platform:
      architecture: arm64
      os: linux
      variant: v8
```

## Why is it called AArch64?

It is arm64, but the more technically correct term. See https://static.docs.arm.com/100878/0100/fundamentals_of_armv8_a_100878_0100_en.pdf

### CODE REVIEW

**Comment by JasonvanBrackel** [comment]
@deniseschannon  I understand we're looking at ARM64, can we get whoever is working on that to review?

**Comment by loganhz** [comment]
Close in favor of https://github.com/rancher/rke-tools/pull/29/files

**Comment by alena1108** [comment]
@ekristen @JasonvanBrackel as arm support requires some re-architecture in our ci/cd process - we are still finalizing the details for that - some of already existing rancher prs would need changes. Would appreciate your review once everything is final.

**Comment by ekristen** [comment]
@alena1108 do you have instructions on how to test? I would like to do this ASAP.

**Comment by alena1108** [comment]
@loganhz @jianghang8421 could you share the instructions on how to test with @ekristen once available?

**Comment by loganhz** [comment]
Sure!

**Pull request closed without merging**
