### PR TITLE
Add workflow to automatically tag and release

### PR DESCRIPTION
**Pull request by superseb**
Workflow to automate what is currently happening manually, it will create a new tag + release on every push to master (and you can run the workflow manually if needed)

- List current latest tag
- Generate new tag by bumping last field by 1 (yes this is not 100% semver bump logic but works and if we ever go minor bump, we can easily adjust)
- Create tag
- Create release from tag

There are some existing Actions but they are either:

- Barely maintained/updated
- Not fully functional for what we need

It also limits us to change or adjust if we need anything, these steps are very clear (imo) and easily adjustable by using simple and readable commands.

Next step in this process would be to automatically bump unreleased Rancher k8s versions with the new tag, but this is the first step.

### CODE REVIEW

**Review by manuelbuil — APPROVED** [review]

**Comment by manuelbuil** [comment]
Interesting that each new commit requires a new release

**Comment by superseb** [comment]
@manuelbuil We can disable that part and just use the workflow manually if needed, there are pros and cons for this:

Pros:
- No manual action needed
- New release for each commit should make testing quicker and easier to identify what commit(s) caused an issue

Cons:
- As many releases as commits (although is it really a con?)
- Possibly dummy releases as no code changes (we can make this process better and exclude creating releases for non-code changes)

I just went with one and as we gather feedback and experience, we can always change it.

**Comment by manuelbuil** [comment]
> @manuelbuil We can disable that part and just use the workflow manually if needed, there are pros and cons for this:
> 
> Pros:
> 
> * No manual action needed
> * New release for each commit should make testing quicker and easier to identify what commit(s) caused an issue
> 
> Cons:
> 
> * As many releases as commits (although is it really a con?)
> * Possibly dummy releases as no code changes (we can make this process better and exclude creating releases for non-code changes)
> 
> I just went with one and as we gather feedback and experience, we can always change it.

Thanks for explaining the pros/cons Seb! I am totally fine with having one commit per release

**Comment by superseb** [comment]
@thomasferrandiz @manuelbuil said you worked on automation pieces before, what do you think about this PR?

**Comment by thomasferrandiz** [comment]
@superseb is the new workflow to release rke1 or just rke-tools?

**Comment by superseb** [comment]
This is the first step in automation and only applies to this repository, rke-tools. Follow up steps would be to automatically bump the rke-tools image in KDM, but we start with little steps. If this is approved, we can basically use this same workflow but without the `push` trigger to manually create a release (candidate) for RKE as well.

**Comment by thomasferrandiz** [comment]
> This is the first step in automation and only applies to this repository, rke-tools. Follow up steps would be to automatically bump the rke-tools image in KDM, but we start with little steps. If this is approved, we can basically use this same workflow but without the `push` trigger to manually create a release (candidate) for RKE as well.

Thanks for the clarification.
In general, I'm not a fan of automatic releases because it can get messy if something problematic is merged but this repository doesn't have a very high activity so I think we're good.

**Review by thomasferrandiz — APPROVED** [review]

**Comment by jakefhyde** [comment]
Great work, only question I have is specific to the versioning, I know that there is a push to start using the `-alpha` designation for releases, do you see this as something that could potentially evolve to be able to tag `-alpha` and `-rc` tags in addition to actual releases?

**Comment by superseb** [comment]
@jakefhyde this was a very easy start as we just want the latest tag and increment the last field. For "more complex" versioning requirements, we can use this as base and extend it to include inputs that can drive the outcome. Especially around source branch and what tag, we can only automate what is properly known/described and its pretty messy/ad-hoc/chaotic currently. So it could just be a manual workflow with checked inputs to begin with and extend from there.

**Pull request closed without merging**
